-- Migration: add_stream_key_to_event_slots
-- Run this in your Supabase SQL Editor if the event_slots table ALREADY EXISTS.
-- All statements are safe to re-run (IF NOT EXISTS / idempotent guards).
--
-- Fixes: "Could not find the 'stream_key' column of 'event_slots' in the schema cache."

-- 1. stream_key — generated by the server at slot-creation time for live events
ALTER TABLE public.event_slots
  ADD COLUMN IF NOT EXISTS stream_key text;

-- 2. stream_url — full RTMP ingest URL, e.g. rtmp://live.studioflow.tv/live/<key>
ALTER TABLE public.event_slots
  ADD COLUMN IF NOT EXISTS stream_url text;

-- 3. submission_id — populated when the slot is created from a submission approval
ALTER TABLE public.event_slots
  ADD COLUMN IF NOT EXISTS submission_id uuid;

-- 4. status — lifecycle state: pending | live | ended
ALTER TABLE public.event_slots
  ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending';

-- 5. Notify Supabase's PostgREST to reload its schema cache immediately
NOTIFY pgrst, 'reload schema';
