-- Migration: add_stream_key_to_event_slots
-- Run this in your Supabase SQL Editor if the event_slots table ALREADY EXISTS
-- (created from the original migration that did not include stream_key/stream_url).
-- All statements are safe to re-run (IF NOT EXISTS / idempotent guards).
--
-- Fixes: "Could not find the 'stream_key' column of 'event_slots' in the schema cache."

-- 1. stream_key — generated by the server at slot-creation time for live events
ALTER TABLE public.event_slots
  ADD COLUMN IF NOT EXISTS stream_key text;

-- 2. stream_url — optional RTMP / HLS ingest URL stored alongside the key
ALTER TABLE public.event_slots
  ADD COLUMN IF NOT EXISTS stream_url text;

-- 3. submission_id — populated when the slot is created from a submission approval
ALTER TABLE public.event_slots
  ADD COLUMN IF NOT EXISTS submission_id uuid;

-- 4. Notify Supabase's schema cache to pick up the new columns immediately.
--    (Supabase auto-refreshes the PostgREST schema cache every ~5 seconds, but
--     running this notify is instant and avoids needing to restart the service.)
NOTIFY pgrst, 'reload schema';
